base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.10"
    namespace: ocp
    tag: openstack-installer
  tools:
    name: "4.10"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.10"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
images:
- dockerfile_literal: |
    FROM tools
    RUN sh -c 'echo -e "[google-cloud-sdk]\nname=Google Cloud SDK\nbaseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg\n       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" > /etc/yum.repos.d/google-cloud-sdk.repo' && \
        PACKAGES="google-cloud-sdk git gzip zip util-linux openssh-clients make gcc" && \
        yum update -y && yum install --setopt=tsflags=nodocs -y $PACKAGES && yum clean all && rm -rf /var/cache/yum/* && \
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install -b /bin && rm -rf ./aws awscliv2.zip && \
        git config --system user.name test-private && git config --system user.email test-private@test.com && \
        chmod g+w /etc/passwd && rm -rf /root/.config/gcloud && \
        pip3 install dotmap minio pyyaml requests && \
        curl -s -k https://dl.google.com/go/go1.17.5.linux-amd64.tar.gz -o go1.17.5.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz && rm -fr go1.17.5.linux-amd64.tar.gz && \
        mkdir -p /tmp/goproject && mkdir -p /tmp/gocache && chmod -R g=u /tmp/goproject && chmod -R g+rw /tmp/goproject && chmod -R g=u /tmp/gocache && chmod -R g+rw /tmp/gocache && \
        curl -s -k https://mirror2.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.10/opm-linux.tar.gz -o opm-linux.tar.gz && \
        tar -C /usr/bin -xzvf opm-linux.tar.gz && rm -fr opm-linux.tar.gz /usr/bin/oc && \
        curl -s -k https://mirror2.openshift.com/pub/openshift-v4/x86_64/clients/operator-sdk/pre-release/operator-sdk-linux-x86_64.tar.gz -o opt-sdk.tar.gz && \
        tar -C /usr/bin -xzvf opt-sdk.tar.gz && rm -fr opt-sdk.tar.gz
  from: tools
  to: tests-private
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.10"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ipi
  interval: 24h
  steps:
    cluster_profile: aws
    env:
      E2E_RUN_TAGS: '@aws-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-aws-ipi-destructive
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      E2E_RUN_TAGS: '@aws-ipi and @destructive'
      TAG_VERSION: '@4.10'
      TEST_FILTERS: ~ChkUpgrade&;~NonPreRelease&;Serial&;~DisconnectedOnly&
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e-destructive
- as: e2e-azure-ipi
  interval: 24h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      E2E_RUN_TAGS: '@azure-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: ipi-azure-post
    pre:
    - chain: ipi-azure-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-azure-upi
  interval: 24h
  steps:
    cluster_profile: azure4
    env:
      E2E_RUN_TAGS: '@azure-upi'
      TAG_VERSION: '@4.10'
    post:
    - chain: upi-azure-post
    pre:
    - chain: upi-azure-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-baremetal-ipi
  interval: 24h
  steps:
    cluster_profile: packet
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
      E2E_RUN_TAGS: '@baremetal-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: baremetalds-ipi-post
    pre:
    - chain: baremetalds-ipi-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-gcp-ipi
  interval: 24h
  steps:
    cluster_profile: gcp
    env:
      E2E_RUN_TAGS: '@gcp-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: ipi-gcp-post
    pre:
    - chain: ipi-gcp-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-gcp-upi
  interval: 24h
  steps:
    cluster_profile: gcp
    env:
      E2E_RUN_TAGS: '@gcp-upi'
      TAG_VERSION: '@4.10'
    post:
    - chain: upi-gcp-post
    pre:
    - chain: upi-gcp-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-openstack-ipi
  interval: 24h
  steps:
    cluster_profile: openstack
    env:
      BASE_DOMAIN: shiftstack.devcluster.openshift.com
      CONFIG_TYPE: minimal
      E2E_RUN_TAGS: '@openstack-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: ipi-openstack-post
    pre:
    - chain: ipi-openstack-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-vsphere-ipi
  interval: 24h
  steps:
    cluster_profile: vsphere
    env:
      E2E_RUN_TAGS: '@vsphere-ipi'
      TAG_VERSION: '@4.10'
    post:
    - chain: ipi-vsphere-post
    pre:
    - chain: ipi-vsphere-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
- as: e2e-vsphere-upi
  interval: 24h
  steps:
    cluster_profile: vsphere
    env:
      E2E_RUN_TAGS: '@vsphere-upi'
      TAG_VERSION: '@4.10'
    post:
    - chain: upi-vsphere-post
    pre:
    - chain: upi-vsphere-pre
    - ref: cucushift-pre
    workflow: cucushift-e2e
zz_generated_metadata:
  branch: master
  org: openshift
  repo: verification-tests
  variant: nightly-4.10
