base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.12"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.12"
    namespace: ocp
    tag: hypershift-operator
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.12"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.12"
  tools:
    name: "4.12"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
tests:
- as: e2e-aws-ipi-p3
  cron: 0 0 */28 * *
  steps:
    cluster_profile: aws-qe
    test:
    - ref: openshift-extended-test
zz_generated_metadata:
  branch: release-4.12
  org: openshift
  repo: openshift-tests-private
  variant: amd64-nightly
