base_images:
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  ocp_builder_rhel-8-golang-1.17-openshift-4.11:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.17-openshift-4.11
  openstack-installer:
    name: "4.11"
    namespace: ocp
    tag: openstack-installer
  tools:
    name: "4.11"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.11"
    namespace: ocp
    tag: upi-installer
binary_build_commands: make all
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
images:
- dockerfile_path: images/Dockerfile
  from: tools
  inputs:
    ocp_builder_rhel-8-golang-1.17-openshift-4.11:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11
  to: tests-private
- dockerfile_literal: |
    FROM src
    RUN curl --silent --location https://rpm.nodesource.com/setup_lts.x | bash - && \
        curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
        PACKAGES="openssh-clients httpd-tools nodejs yarn xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib" && \
        yum install --setopt=tsflags=nodocs -y $PACKAGES && \
        yum clean all && rm -rf /var/cache/yum/*
  from: src
  to: tests-private-ui
promotion:
  excluded_images:
  - tests-private
  - tests-private-ui
  name: "4.11"
  namespace: ocp
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  bin:
    requests:
      cpu: "2"
      memory: 8Gi
  e2e-aws:
    requests:
      cpu: "4"
      memory: 4Gi
test_binary_build_commands: make test
tests:
- as: title-check
  commands: make name-check
  container:
    from: src
- as: extended-baremetal-ipi-parallel
  cron: 0 6 * * *
  steps:
    cluster_profile: equinix-ocp-metal
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
    post:
    - chain: baremetalds-ipi-post
    pre:
    - chain: baremetalds-ipi-pre
    test:
    - ref: openshift-extended-test
- as: extended-gcp-ipi
  cron: 0 8 * * *
  steps:
    cluster_profile: aws
    env:
      TEST_SCENRAIOS: |
        NODE|OTA|PerfScale|Windows_Containers|Cluster_Observability
    post:
    - chain: ipi-aws-post
    pre:
    - chain: ipi-aws-pre
    test:
    - ref: openshift-extended-test
- as: extended-openstack-ipi
  cron: 0 12 * * *
  steps:
    cluster_profile: openstack
    env:
      BASE_DOMAIN: shiftstack.devcluster.openshift.com
      CONFIG_TYPE: minimal
      TEST_FILTERS: ~ChkUpgrade&;~NonPreRelease&;~Serial&;~Disruptive&;~DisconnectedOnly&
      TEST_SCENRAIOS: STORAGE
    post:
    - chain: ipi-openstack-post
    pre:
    - chain: ipi-openstack-pre
    test:
    - ref: openshift-extended-test
- as: extended-gcp-upi-parallel
  cron: 0 */24 * * *
  steps:
    cluster_profile: gcp
    env:
      TEST_PARALLEL: "2"
      TEST_SCENRAIOS: |
        Security_and_Compliance
    post:
    - chain: upi-gcp-post
    pre:
    - chain: upi-gcp-pre
    test:
    - ref: openshift-extended-test
- as: extended-vsphere-upi
  cron: 0 16 * * *
  steps:
    cluster_profile: vsphere
    post:
    - chain: upi-vsphere-post
    pre:
    - chain: upi-vsphere-pre
    test:
    - ref: openshift-extended-test
zz_generated_metadata:
  branch: master
  org: openshift
  repo: openshift-tests-private
